//
//  State.swift
//  AsyncTimer
//
//  Created by CodingIran on 2025/5/24.
//

import Foundation

// extension AsyncTimer.State: CustomDebugStringConvertible, Equatable {
//     public var debugDescription: String {
//         switch self {
//         case .idle: return "idle"
//         case .running: return "running"
//         case .executing: return "executing"
//         case .finished: return "finished"
//         }
//     }

//     public static func == (lhs: AsyncTimer.State, rhs: AsyncTimer.State) -> Bool {
//         switch (lhs, rhs) {
//         case (.idle, .idle): return true
//         case (.running, .running): return true
//         case (.executing, .executing): return true
//         case (.finished, .finished): return true
//         default: return false
//         }
//     }
// }
